const bahanMapping = {
  // Bumbu Dasar
  "bawang putih": "garlic",
  "bawang merah": "shallot",
  "daun bawang": "green onion",
  "cabe merah": "red chili",
  "cabe hijau": "green chili",
  jahe: "ginger",
  kunyit: "turmeric",
  lengkuas: "galangal",
  serai: "lemongrass",
  kemiri: "candlenut",
  "daun salam": "bay leaf",
  "daun jeruk": "kaffir lime leaf",
  ketumbar: "coriander",
  jintan: "cumin",
  lada: "pepper",
  garam: "salt",
  gula: "sugar",
  "gula merah": "palm sugar",
  "gula aren": "coconut sugar",
  kecap: "soy sauce",
  "kecap manis": "sweet soy sauce",
  terasi: "shrimp paste",
  santan: "coconut milk",
  "asam jawa": "tamarind",
  pala: "nutmeg",
  cengkeh: "clove",
  kapulaga: "cardamom",
  "kayu manis": "cinnamon",
  "biji pala": "mace seed",
  vanili: "vanilla",
  "daun kari": "curry leaf",
  "bawang bombay": "onion",
  adas: "fennel",
  wijen: "sesame seed",
  "daun pandan": "pandan leaf",
  "daun mint": "mint leaf",
  "serai bubuk": "lemongrass powder",

  // Sayuran
  tomat: "tomato",
  kentang: "potato",
  bayam: "spinach",
  wortel: "carrot",
  jagung: "corn",
  kubis: "cabbage",
  timun: "cucumber",
  brokoli: "broccoli",
  kembangkol: "cauliflower",
  terong: "eggplant",
  labu: "pumpkin",
  kangkung: "water spinach",
  pare: "bitter melon",
  "daun singkong": "cassava leaf",
  selada: "lettuce",
  "daun kemangi": "basil leaf",
  "ubi jalar": "sweet potato",
  lobak: "radish",
  buncis: "green bean",
  "kacang panjang": "long bean",
  jamur: "mushroom",
  "jamur kuping": "wood ear mushroom",
  "jamur tiram": "oyster mushroom",
  "selada air": "watercress",
  "daun katuk": "sweet leaf",
  "daun pepaya": "papaya leaf",
  talas: "taro",
  "kacang merah": "red bean",
  "kacang polong": "green pea",
  "kelapa sawit": "palm fruit",
  "daun kelor": "moringa leaf",
  "daun bawang prei": "leek",
  "ubi kayu": "cassava root",
  sukun: "breadfruit",
  petai: "stink bean",
  jengkol: "dogfruit",
  kencur: "aromatic ginger",
  "daun ginseng": "ginseng leaf",
  "biji labu": "pumpkin seed",
  "biji wijen": "sesame seed",
  "biji bunga matahari": "sunflower seed",
  "biji rami": "flaxseed",
  "biji chia": "chia seed",
  "sagu basah": "wet sago",
  "teh hijau": "green tea",
  "teh hitam": "black tea",
  "teh putih": "white tea",
  "jahe merah": "red ginger",
  "kopi robusta": "robusta coffee",
  "kopi arabika": "arabica coffee",
  "gula kelapa": "coconut sugar",
  "gula tebu": "cane sugar",
  "daun katuk": "sweet leaf",
  "daun sirih": "betel leaf",
  "daun singkong muda": "young cassava leaf",
  "daun beluntas": "beluntas leaf",
  "daun bawang bombay": "spring onion",
  "umbi gadung": "dioscorea tuber",
  "umbi porang": "konjac tuber",
  "umbi gembili": "lesser yam",
  "sagu lempeng": "sago block",
  "kopi luwak": "civet coffee",
  "biji cokelat": "cocoa bean",
  "kol ungu": "purple cabbage",
  selasih: "basil seed",
  "terong belanda": "tamarillo",
  "bunga telang": "butterfly pea flower",
  kecipir: "winged bean",
  "labu siam": "chayote",
  "belimbing wuluh": "bilimbi",
  matoa: "pometia fruit",
  cempokak: "turkey berry",
  "asinan buah": "pickled fruit",
  "kue cucur": "cucur cake",
  "kue lapis": "layer cake",
  "kue bolu": "sponge cake",
  "ubi cilembu": "honey sweet potato",
  "lempok durian": "durian toffee",
  getuk: "cassava cake",
  "onde-onde": "sesame ball",
  "kacang gude": "pigeon pea",
  "kacang tolo": "black-eyed pea",
  "kacang koro": "lima bean",
  "kacang edamame": "edamame",
  "kacang kenari": "walnut",
  "pandan wangi": "fragrant pandan",
  "gula semut": "granulated palm sugar",
  "air asam": "tamarind water",
  "air mawar": "rose water",
  "tepung mocaf": "modified cassava flour",
  "tepung panir": "bread crumbs",
  "tepung hunkwe": "mung bean starch",
  "tepung maizena": "corn flour",
  "beras ketan putih": "white glutinous rice",
  "beras ketan hitam": "black glutinous rice",
  "beras mentik susu": "mentik susu rice",
  "beras pandan wangi": "pandan fragrant rice",
  "beras raja lele": "raja lele rice",
  "daun bawang kecil": "chives",
  "bawang daun": "welsh onion",
  "daun seledri": "celery leaf",
  "daun bawang perai": "leek",
  "ubi talas": "taro root",
  "talas beneng": "giant taro",
  "umbi garut": "arrowroot",
  "umbi suweg": "elephant foot yam",
  "bawang kucai": "garlic chives",
  "jahe bubuk": "ginger powder",
  "kunyit bubuk": "turmeric powder",
  "serai segar": "fresh lemongrass",
  "serai kering": "dried lemongrass",
  "daun sirih merah": "red betel leaf",
  "daun pegagan": "gotu kola leaf",
  "daun kelor kering": "dried moringa leaf",
  "daun jeruk purut": "kaffir lime leaves",
  "daun salam kering": "dried bay leaf",
  "biji ketapang": "tropical almond",
  "biji kenari": "candlenut seed",
  "biji mahoni": "mahogany seed",
  "biji jintan hitam": "black cumin seed",
  "biji kemiri": "candlenut seed",
  "biji ketumbar": "coriander seed",
  "biji vanili": "vanilla bean",
  "bunga lawang": "star anise",
  "bunga cengkeh": "clove flower",
  "bunga pepaya": "papaya flower",
  "bunga turi": "hummingbird flower",
  "bunga kol": "cauliflower",
  "buah maja": "bael fruit",
  "buah keluwak": "black nut",
  "buah matoa": "pometia fruit",
  "buah lobi-lobi": "lovi-lovi fruit",
  "buah cermai": "otaheite gooseberry",
  "buah kepel": "kepel fruit",
  "buah mundu": "mundu fruit",
  "buah asam kandis": "garcinia fruit",
  "buah kedondong": "ambarella",
  "buah kemang": "wild mango",
  "buah kecapi": "sandoricum fruit",
  "buah bisbul": "velvet apple",
  "buah jengkol": "dogfruit",
  "buah petai": "stink bean",
  "buah sawo": "sapodilla",
  "buah buni": "bignay fruit",
  "buah gandaria": "marian plum",
  "buah kemiri": "candlenut",
  "buah sukun": "breadfruit",
  "buah ciplukan": "ground cherry",
  "buah talok": "jamaican cherry",
  "buah menteng": "baccaurea fruit",
  "buah ketapang": "tropical almond fruit",
  "cabe rawit merah": "red bird's eye chili",
  "cabe rawit hijau": "green bird's eye chili",
  "cabe gendot": "fat chili",
  "cabe setan": "devil's chili",
  "cabe domba": "curly chili",
  "lada hitam": "black pepper",
  "lada putih": "white pepper",
  "garam himalaya": "himalayan salt",
  "garam laut": "sea salt",
  "garam dapur": "table salt",
  "gula jawa": "palm sugar",
  "gula aren cair": "liquid palm sugar",
  "madu hutan": "wild honey",
  "madu klanceng": "stingless bee honey",
  "santan instan": "instant coconut milk",
  "santan bubuk": "coconut milk powder",
  "susu kedelai": "soy milk",
  "susu oat": "oat milk",
  "susu almond": "almond milk",
  "krim kental": "heavy cream",
  "krim kocok": "whipped cream",
  "minyak kelapa": "coconut oil",
  "minyak zaitun": "olive oil",
  "minyak wijen": "sesame oil",
  "minyak jagung": "corn oil",
  "minyak sawit": "palm oil",
  "minyak kedelai": "soybean oil",
  "minyak canola": "canola oil",
  "minyak biji anggur": "grape seed oil",
  "minyak bunga matahari": "sunflower oil",
  "cuka apel": "apple cider vinegar",
  "cuka beras": "rice vinegar",
  "cuka balsamic": "balsamic vinegar",
  "cuka kelapa": "coconut vinegar",
  "tepung beras merah": "brown rice flour",
  "tepung beras hitam": "black rice flour",
  "tepung jagung organik": "organic corn flour",
  "tepung gandum utuh": "whole wheat flour",
  "tepung kentang": "potato flour",
  "tepung kedelai": "soy flour",
  "tepung durian": "durian flour",
  "tepung pisang": "banana flour",
  "tepung ubi jalar": "sweet potato flour",
  "pasta pandan": "pandan paste",
  "pasta vanila": "vanilla paste",
  "pasta stroberi": "strawberry paste",
  "pasta cokelat": "chocolate paste",
  "essence kelapa": "coconut essence",
  "essence kopi": "coffee essence",
  "essence durian": "durian essence",
  "ragi instan": "instant yeast",
  "ragi tape": "tape yeast",
  "ragi roti": "bread yeast",
  "baking soda": "baking soda",
  "baking powder": "baking powder",
  "soda kue": "baking soda",
  "pengembang kue": "cake leavening agent",
  "pengemulsi kue": "cake emulsifier",
  "agar-agar bubuk": "agar powder",
  "jelly bubuk": "jelly powder",
  "puding instan": "instant pudding mix",
  "selai kacang": "peanut butter",
  "selai stroberi": "strawberry jam",
  "selai cokelat": "chocolate spread",
  "selai nanas": "pineapple jam",
  "cokelat bubuk": "cocoa powder",
  "cokelat batangan": "chocolate bar",
  "dark chocolate": "dark chocolate",
  "white chocolate": "white chocolate",
  "cokelat masak": "cooking chocolate",
  "sirup gula": "sugar syrup",
  "sirup frambozen": "frambozen syrup",
  "sirup cocopandan": "cocopandan syrup",
  "sirup melon": "melon syrup",
  "sirup leci": "lychee syrup",
  "sirup markisa": "passion fruit syrup",
  "sirup mangga": "mango syrup",
  "sirup sirsak": "soursop syrup",

  // Protein
  "daging sapi": "beef",
  sapi: "beef",
  "daging ayam": "chicken",
  ayam: "chicken",
  ikan: "fish",
  "daging kambing": "goat meat",
  kambing: "goat meat",
  "daging babi": "pork",
  babi: "pork",
  udang: "shrimp",
  cumi: "squid",
  kerang: "clam",
  kepiting: "crab",
  telur: "egg",
  tahu: "tofu",
  tempe: "tempeh",
  "daging bebek": "duck meat",
  bebek: "duck meat",
  "ikan teri": "anchovy",
  "ikan asin": "salted fish",
  "ikan tuna": "tuna",
  "ikan salmon": "salmon",
  "ikan lele": "catfish",
  belut: "eel",
  "ikan kembung": "mackerel",
  "ikan patin": "pangasius",
  "ikan bandeng": "milkfish",

  // Produk Susu
  keju: "cheese",
  susu: "milk",
  yoghurt: "yogurt",
  mentega: "butter",
  krim: "cream",
  "susu kental manis": "condensed milk",
  "susu evaporasi": "evaporated milk",
  margarin: "margarine",
  krimer: "creamer",

  // Bahan Kering
  tepung: "flour",
  "tepung terigu": "wheat flour",
  "tepung beras": "rice flour",
  "tepung tapioka": "tapioca flour",
  "tepung jagung": "cornstarch",
  "tepung ketan": "glutinous rice flour",
  "tepung sagu": "sago flour",
  roti: "bread",
  pasta: "pasta",
  mie: "noodle",
  bihun: "rice vermicelli",
  sohun: "glass noodle",
  sagu: "sago",
  singkong: "cassava",
  "ubi ungu": "purple yam",

  // Buah
  pisang: "banana",
  apel: "apple",
  mangga: "mango",
  jeruk: "orange",
  lemon: "lemon",
  alpukat: "avocado",
  nanas: "pineapple",
  pepaya: "papaya",
  stroberi: "strawberry",
  anggur: "grape",
  kelengkeng: "longan",
  sirsak: "soursop",
  markisa: "passion fruit",
  nangka: "jackfruit",
  salak: "snake fruit",
  manggis: "mangosteen",
  "jambu air": "rose apple",
  "jambu biji": "guava",
  semangka: "watermelon",
  melon: "melon",
  cempedak: "chempedak",
  duku: "lanzones",
  kesemek: "persimmon",
  "buah naga": "dragon fruit",
  rambutan: "rambutan",

  // Lain-lain
  madu: "honey",
  cokelat: "chocolate",
  kopi: "coffee",
  teh: "tea",
  kacang: "peanut",
  "kacang tanah": "peanut",
  "kacang hijau": "mung bean",
  "kacang kedelai": "soybean",
  "kacang almond": "almond",
  "kacang mete": "cashew nut",
  kelapa: "coconut",
  "kelapa parut": "grated coconut",
  "kelapa muda": "young coconut",
  air: "water",
  nasi: "rice",
  "beras merah": "brown rice",
  "beras ketan": "sticky rice",
  "beras hitam": "black rice",
  "gula batu": "rock sugar",
  "gula jagung": "corn sugar",
  "air kelapa": "coconut water",
  "agar-agar": "agar",
  "sagu mutiara": "tapioca pearl",
  cincau: "grass jelly",
};

export default bahanMapping;
